#!/bin/bash
#
# ### NOTE
#
# * File mode
#   * If the git hook file is not allowed to execute, git ignores the file.
#   * $ chmod u+x commit-msg
# * commitlint --edit
#   * "--edit" option reads last commit message from ".git/COMMIT_EDITMSG".
#   * Git executes the hook file on the repository root directory.
#     * From these, it does not matter which direcotry that making the commit.
#   * When git executes the hook file, git sets ".git/COMMIT_EDITMSG" to $1.
#   * It returns the same results by the following command.
#     * $ cat "$1" | commitlint
#

command -v commitlint 1>/dev/null 2>/dev/null
readonly command_is_found=$?

if [ "$command_is_found" == 0 ]; then
  echo "[commit-msg hook] do commitlint"
  # Use "--extends" option in order to avoid the following error.
  #
  #   Error: Cannot find module "@commitlint/config-conventional"
  #
  # ref. https://github.com/conventional-changelog/commitlint/issues/613#issuecomment-1061807137
  commitlint_config="$HOME/.config/commitlint/commitlint.config.js"
  commitlint_config_to_extend="$(npm root -g)/@commitlint/config-conventional"

  commitlint --edit --config "$commitlint_config" --extends "$commitlint_config_to_extend"
else
  echo "[commit-msg hook] skip commitlint (because it is not installed)"
fi
